package crypto

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
)

// Cross-language byte-exactness fixture file (ADR-080).
//
// Generated by scripts/beacon/generate_cross_lang_fixtures.py in the netbrain
// repo and committed under tests/fixtures/cross_lang/cross_lang_fixtures.json.
// Path resolution is robust under split-mount CI rigs (per the
// add-multi-mode-ingestion retro learning): NETBRAIN_BEACON_REPO_ROOT env
// override → walk up from __file__ looking for go.mod → walk up from cwd.

type fixtureMeta struct {
	GeneratedAt         string `json:"generated_at"`
	Generator           string `json:"generator"`
	Purpose             string `json:"purpose"`
	RefreshPolicy       string `json:"refresh_policy"`
	NSBeaconBatch       string `json:"ns_beacon_batch"`
	Ed25519PubkeyRawB64 string `json:"ed25519_pubkey_raw_b64"`
	EnvelopeVersionByte int    `json:"envelope_version_byte"`
}

type uuidCase struct {
	CaseID                 string `json:"case_id"`
	BeaconID               string `json:"beacon_id"`
	PlaintextB64           string `json:"plaintext_b64"`
	ExpectedIdempotencyKey string `json:"expected_idempotency_key"`
}

type aesCase struct {
	CaseID              string `json:"case_id"`
	DEKB64              string `json:"dek_b64"`
	DEKVersion          int    `json:"dek_version"`
	IVB64               string `json:"iv_b64"`
	IdempotencyKey      string `json:"idempotency_key"`
	AADB64              string `json:"aad_b64"`
	PlaintextB64        string `json:"plaintext_b64"`
	ExpectedEnvelopeB64 string `json:"expected_envelope_b64"`
}

type ed25519Case struct {
	CaseID               string          `json:"case_id"`
	Payload              json.RawMessage `json:"payload"`
	ExpectedCanonicalB64 string          `json:"expected_canonical_b64"`
	ExpectedSignatureB64 string          `json:"expected_signature_b64"`
}

type canonicalCase struct {
	CaseID               string          `json:"case_id"`
	Payload              json.RawMessage `json:"payload"`
	ExpectedCanonicalB64 string          `json:"expected_canonical_b64"`
}

type fixtures struct {
	Meta            fixtureMeta     `json:"_meta"`
	UUIDIdempotency []uuidCase      `json:"uuid_v5_idempotency"`
	AESGCMEnvelope  []aesCase       `json:"aes_gcm_envelope"`
	Ed25519Bundle   []ed25519Case   `json:"ed25519_signed_bundle"`
	CanonicalJSON   []canonicalCase `json:"canonical_json"`
}

// findRepoRoot walks up from the test source file looking for go.mod.
// Mirrors the _find_repo_root() pattern documented in the
// add-multi-mode-ingestion retrospective for split-mount-safe path
// resolution.
func findRepoRoot(t *testing.T) string {
	t.Helper()

	if env := os.Getenv("NETBRAIN_BEACON_REPO_ROOT"); env != "" {
		return env
	}

	// Walk up from cwd.
	wd, err := os.Getwd()
	require.NoError(t, err)
	dir := wd
	for i := 0; i < 8; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Fatalf("findRepoRoot: no go.mod found above %s", wd)
	return ""
}

func loadFixtures(t *testing.T) *fixtures {
	t.Helper()
	root := findRepoRoot(t)
	path := filepath.Join(root, "tests", "fixtures", "cross_lang", "cross_lang_fixtures.json")
	raw, err := os.ReadFile(path) //nolint:gosec // test-only path; not user-controlled
	require.NoError(t, err, "read fixture file at %s", path)

	var f fixtures
	require.NoError(t, json.Unmarshal(raw, &f))
	require.NotEmpty(t, f.UUIDIdempotency, "fixture file has no UUIDv5 cases")
	require.NotEmpty(t, f.AESGCMEnvelope, "fixture file has no AES-GCM cases")
	require.NotEmpty(t, f.Ed25519Bundle, "fixture file has no ed25519 cases")
	require.NotEmpty(t, f.CanonicalJSON, "fixture file has no canonical-JSON cases")
	return &f
}

func mustB64(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	require.NoError(t, err)
	return b
}

// --------------------- UUIDv5 idempotency-key ---------------------

func TestCrossLangUUIDv5(t *testing.T) {
	f := loadFixtures(t)

	// Namespace pin invariant — if this fails, _every_ subsequent UUID case
	// would too. Check first to fail-fast with a clear message.
	require.Equal(t, NSBeaconBatch.String(), f.Meta.NSBeaconBatch,
		"namespace UUID drifted between Python and Go")

	for _, c := range f.UUIDIdempotency {
		t.Run(c.CaseID, func(t *testing.T) {
			beaconID := uuid.MustParse(c.BeaconID)
			pt := mustB64(t, c.PlaintextB64)
			expected := uuid.MustParse(c.ExpectedIdempotencyKey)

			got := DeriveBatchIdempotencyKey(beaconID, pt)
			require.Equal(t, expected, got,
				"R-1 BYTE-EXACTNESS DRIFT: case %q derived %s but Python expected %s — "+
					"check the hex.EncodeToString step in DeriveBatchIdempotencyKey",
				c.CaseID, got, expected)
		})
	}
}

// --------------------- AES-256-GCM envelope ---------------------

func TestCrossLangAESEnvelope(t *testing.T) {
	f := loadFixtures(t)

	require.Equal(t, int(envelopeVersionByte), f.Meta.EnvelopeVersionByte,
		"envelope version byte drifted between Python and Go")

	for _, c := range f.AESGCMEnvelope {
		t.Run(c.CaseID, func(t *testing.T) {
			dek := mustB64(t, c.DEKB64)
			iv := mustB64(t, c.IVB64)
			aad := mustB64(t, c.AADB64)
			pt := mustB64(t, c.PlaintextB64)
			expected := mustB64(t, c.ExpectedEnvelopeB64)

			// Sanity-check the AAD shape matches MakeAAD's output. If the
			// fixture's AAD is wrong, every envelope derivation downstream
			// is also wrong.
			idempotencyKey := uuid.MustParse(c.IdempotencyKey)
			expectedAAD := MakeAAD(byte(c.DEKVersion), idempotencyKey)
			require.True(t, bytes.Equal(expectedAAD, aad),
				"AAD shape drifted: MakeAAD(%d, %s)=%x but fixture says %x",
				c.DEKVersion, idempotencyKey, expectedAAD, aad)

			got, err := encryptWithIV(pt, dek, byte(c.DEKVersion), iv, aad)
			require.NoError(t, err)
			require.True(t, bytes.Equal(expected, got),
				"envelope byte mismatch: case %q\n  expected %x\n  got      %x", c.CaseID, expected, got)

			// Round-trip: decrypting our own envelope must yield the original plaintext.
			pt2, err := Decrypt(got, dek, aad)
			require.NoError(t, err)
			require.True(t, bytes.Equal(pt, pt2), "self round-trip plaintext mismatch")

			// Round-trip: decrypting the Python-emitted envelope must yield the original plaintext.
			pt3, err := Decrypt(expected, dek, aad)
			require.NoError(t, err)
			require.True(t, bytes.Equal(pt, pt3), "Python-envelope round-trip plaintext mismatch")
		})
	}
}

// --------------------- ed25519 signed-bundle ---------------------

func TestCrossLangEd25519(t *testing.T) {
	f := loadFixtures(t)

	pub, err := LoadPublicKeyRaw(mustB64(t, f.Meta.Ed25519PubkeyRawB64))
	require.NoError(t, err)

	for _, c := range f.Ed25519Bundle {
		t.Run(c.CaseID, func(t *testing.T) {
			expectedCanonical := mustB64(t, c.ExpectedCanonicalB64)

			// 1) Canonical-JSON byte-exactness.
			got, err := CanonicalizeRawJSON(c.Payload)
			require.NoError(t, err)
			require.True(t, bytes.Equal(expectedCanonical, got),
				"canonical JSON drifted:\n  expected %q\n  got      %q",
				string(expectedCanonical), string(got))

			// 2) Signature verifies against the canonical bytes we computed.
			var payload any
			require.NoError(t, json.Unmarshal(c.Payload, &payload))
			require.NoError(t, VerifyPayload(pub, payload, c.ExpectedSignatureB64))
		})
	}
}

// --------------------- canonical-JSON only ---------------------

func TestCrossLangCanonicalJSON(t *testing.T) {
	f := loadFixtures(t)

	for _, c := range f.CanonicalJSON {
		t.Run(c.CaseID, func(t *testing.T) {
			expected := mustB64(t, c.ExpectedCanonicalB64)

			got, err := CanonicalizeRawJSON(c.Payload)
			require.NoError(t, err)
			require.True(t, bytes.Equal(expected, got),
				"canonical JSON drifted on case %q:\n  expected %q\n  got      %q",
				c.CaseID, string(expected), string(got))
		})
	}
}
