// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerJwtScopes      = "bearerJwt.Scopes"
	BootstrapTokenScopes = "bootstrapToken.Scopes"
	MTlsScopes           = "mTls.Scopes"
)

// Defines values for BeaconConfigCollectorsNetflowAcceptVersions.
const (
	Ipfix BeaconConfigCollectorsNetflowAcceptVersions = "ipfix"
	V5    BeaconConfigCollectorsNetflowAcceptVersions = "v5"
	V9    BeaconConfigCollectorsNetflowAcceptVersions = "v9"
)

// Defines values for BeaconConfigCollectorsSnmpV3AuthProtocol.
const (
	SHA    BeaconConfigCollectorsSnmpV3AuthProtocol = "SHA"
	SHA256 BeaconConfigCollectorsSnmpV3AuthProtocol = "SHA256"
	SHA512 BeaconConfigCollectorsSnmpV3AuthProtocol = "SHA512"
)

// Defines values for BeaconConfigCollectorsSnmpV3PrivProtocol.
const (
	AES128 BeaconConfigCollectorsSnmpV3PrivProtocol = "AES128"
	AES256 BeaconConfigCollectorsSnmpV3PrivProtocol = "AES256"
)

// Defines values for BeaconConfigCollectorsSnmpVersion.
const (
	V2c BeaconConfigCollectorsSnmpVersion = "v2c"
	V3  BeaconConfigCollectorsSnmpVersion = "v3"
)

// Defines values for BeaconConfigStoreEvictionPriority.
const (
	Flows BeaconConfigStoreEvictionPriority = "flows"
	Logs  BeaconConfigStoreEvictionPriority = "logs"
	Snmp  BeaconConfigStoreEvictionPriority = "snmp"
)

// Defines values for BeaconMetadataOs.
const (
	Darwinamd64  BeaconMetadataOs = "darwin/amd64"
	Darwinarm64  BeaconMetadataOs = "darwin/arm64"
	Linuxamd64   BeaconMetadataOs = "linux/amd64"
	Linuxarm64   BeaconMetadataOs = "linux/arm64"
	Windowsamd64 BeaconMetadataOs = "windows/amd64"
)

// Defines values for BeaconStatusStatus.
const (
	Active  BeaconStatusStatus = "active"
	Expired BeaconStatusStatus = "expired"
	Revoked BeaconStatusStatus = "revoked"
)

// Defines values for CertStatusResponseRecommendedAction.
const (
	None   CertStatusResponseRecommendedAction = "none"
	Rotate CertStatusResponseRecommendedAction = "rotate"
)

// BeaconConfig defines model for BeaconConfig.
type BeaconConfig struct {
	BeaconMetadata *map[string]interface{} `json:"beacon_metadata,omitempty"`
	Collectors     BeaconConfigCollectors  `json:"collectors"`
	Heartbeat      BeaconConfigHeartbeat   `json:"heartbeat"`
	Store          BeaconConfigStore       `json:"store"`
	Transport      BeaconConfigTransport   `json:"transport"`
}

// BeaconConfigCollectors defines model for BeaconConfigCollectors.
type BeaconConfigCollectors struct {
	ConfigCollection BeaconConfigCollectorsConfigCollection `json:"config_collection"`
	Netflow          BeaconConfigCollectorsNetflow          `json:"netflow"`
	Snmp             BeaconConfigCollectorsSnmp             `json:"snmp"`
	Syslog           BeaconConfigCollectorsSyslog           `json:"syslog"`
}

// BeaconConfigCollectorsConfigCollection defines model for BeaconConfigCollectorsConfigCollection.
type BeaconConfigCollectorsConfigCollection struct {
	Devices      *[]BeaconConfigDevice `json:"devices,omitempty"`
	Enabled      bool                  `json:"enabled"`
	ScheduleCron string                `json:"schedule_cron"`
}

// BeaconConfigCollectorsNetflow defines model for BeaconConfigCollectorsNetflow.
type BeaconConfigCollectorsNetflow struct {
	AcceptVersions *[]BeaconConfigCollectorsNetflowAcceptVersions `json:"accept_versions,omitempty"`
	Enabled        bool                                           `json:"enabled"`
	UdpListen      *string                                        `json:"udp_listen,omitempty"`
}

// BeaconConfigCollectorsNetflowAcceptVersions defines model for BeaconConfigCollectorsNetflow.AcceptVersions.
type BeaconConfigCollectorsNetflowAcceptVersions string

// BeaconConfigCollectorsSnmp defines model for BeaconConfigCollectorsSnmp.
type BeaconConfigCollectorsSnmp struct {
	DeviceIps           []string  `json:"device_ips"`
	Enabled             bool      `json:"enabled"`
	Oids                *[]string `json:"oids,omitempty"`
	PollIntervalSeconds int       `json:"poll_interval_seconds"`

	// V3AuthKeyEncrypted AES-256-GCM-encrypted with the beacon's DEK.
	V3AuthKeyEncrypted *string                                   `json:"v3_auth_key_encrypted"`
	V3AuthProtocol     *BeaconConfigCollectorsSnmpV3AuthProtocol `json:"v3_auth_protocol"`
	V3PrivKeyEncrypted *string                                   `json:"v3_priv_key_encrypted"`
	V3PrivProtocol     *BeaconConfigCollectorsSnmpV3PrivProtocol `json:"v3_priv_protocol"`
	V3User             *string                                   `json:"v3_user"`
	Version            BeaconConfigCollectorsSnmpVersion         `json:"version"`
}

// BeaconConfigCollectorsSnmpV3AuthProtocol defines model for BeaconConfigCollectorsSnmp.V3AuthProtocol.
type BeaconConfigCollectorsSnmpV3AuthProtocol string

// BeaconConfigCollectorsSnmpV3PrivProtocol defines model for BeaconConfigCollectorsSnmp.V3PrivProtocol.
type BeaconConfigCollectorsSnmpV3PrivProtocol string

// BeaconConfigCollectorsSnmpVersion defines model for BeaconConfigCollectorsSnmp.Version.
type BeaconConfigCollectorsSnmpVersion string

// BeaconConfigCollectorsSyslog defines model for BeaconConfigCollectorsSyslog.
type BeaconConfigCollectorsSyslog struct {
	Enabled   bool    `json:"enabled"`
	TcpListen *string `json:"tcp_listen,omitempty"`
	UdpListen *string `json:"udp_listen,omitempty"`
}

// BeaconConfigDevice defines model for BeaconConfigDevice.
type BeaconConfigDevice struct {
	DeviceId string `json:"device_id"`
	Host     string `json:"host"`

	// SshKeyEncrypted AES-256-GCM-encrypted with the beacon's DEK.
	SshKeyEncrypted string `json:"ssh_key_encrypted"`
	SshUser         string `json:"ssh_user"`
	Vendor          string `json:"vendor"`
}

// BeaconConfigHeartbeat defines model for BeaconConfigHeartbeat.
type BeaconConfigHeartbeat struct {
	IntervalSeconds *int `json:"interval_seconds,omitempty"`
	JitterSeconds   *int `json:"jitter_seconds,omitempty"`
}

// BeaconConfigResponse defines model for BeaconConfigResponse.
type BeaconConfigResponse struct {
	Config BeaconConfig `json:"config"`

	// ConfigHash sha256 of canonicalized JSON config.
	ConfigHash string `json:"config_hash"`
}

// BeaconConfigStore defines model for BeaconConfigStore.
type BeaconConfigStore struct {
	EvictionPriority *[]BeaconConfigStoreEvictionPriority `json:"eviction_priority,omitempty"`
	MaxAgeSeconds    *int                                 `json:"max_age_seconds,omitempty"`
	MaxSizeBytes     *int                                 `json:"max_size_bytes,omitempty"`
}

// BeaconConfigStoreEvictionPriority defines model for BeaconConfigStore.EvictionPriority.
type BeaconConfigStoreEvictionPriority string

// BeaconConfigTransport defines model for BeaconConfigTransport.
type BeaconConfigTransport struct {
	ConfigBatchMaxAgeSeconds *int `json:"config_batch_max_age_seconds,omitempty"`
	FlowBatchMaxAgeSeconds   *int `json:"flow_batch_max_age_seconds,omitempty"`
	FlowBatchMaxBytes        *int `json:"flow_batch_max_bytes,omitempty"`
	LogBatchMaxAgeSeconds    *int `json:"log_batch_max_age_seconds,omitempty"`
	LogBatchMaxBytes         *int `json:"log_batch_max_bytes,omitempty"`
	RetryMaxSeconds          *int `json:"retry_max_seconds,omitempty"`
}

// BeaconEnrollRequest defines model for BeaconEnrollRequest.
type BeaconEnrollRequest struct {
	BeaconMetadata BeaconMetadata `json:"beacon_metadata"`
	BootstrapToken string         `json:"bootstrap_token"`

	// CsrPem PEM-encoded CSR with EMPTY Subject (server rebuilds identity per ADR-067).
	CsrPem string `json:"csr_pem"`
}

// BeaconEnrollResponse defines model for BeaconEnrollResponse.
type BeaconEnrollResponse struct {
	BeaconId       openapi_types.UUID `json:"beacon_id"`
	CaCertPem      string             `json:"ca_cert_pem"`
	ClientCertPem  string             `json:"client_cert_pem"`
	ConfigEndpoint string             `json:"config_endpoint"`
	DataEndpoint   string             `json:"data_endpoint"`

	// DataKeyB64 Base64 of 32 random bytes. Per-install AES-256-GCM DEK. Transmitted ONCE.
	DataKeyB64               []byte `json:"data_key_b64"`
	DataKeyVersion           int    `json:"data_key_version"`
	HeartbeatIntervalSeconds int    `json:"heartbeat_interval_seconds"`
	LogBatchMaxAgeSeconds    int    `json:"log_batch_max_age_seconds"`
	LogBatchMaxBytes         int    `json:"log_batch_max_bytes"`
}

// BeaconHeartbeatRequest defines model for BeaconHeartbeatRequest.
type BeaconHeartbeatRequest struct {
	BeaconVersion       string                `json:"beacon_version"`
	ClockSkewSeconds    float32               `json:"clock_skew_seconds"`
	DeviceLatencyProbes *[]DeviceLatencyProbe `json:"device_latency_probes,omitempty"`
	EvictionsTotal      map[string]int        `json:"evictions_total"`
	PendingConfigHash   *string               `json:"pending_config_hash"`
	QueueDepths         map[string]int        `json:"queue_depths"`
	ReplayLagSeconds    float32               `json:"replay_lag_seconds"`
	StoreSizeBytes      int                   `json:"store_size_bytes"`
	Timestamp           time.Time             `json:"timestamp"`
	UptimeSeconds       int                   `json:"uptime_seconds"`
}

// BeaconListResponse defines model for BeaconListResponse.
type BeaconListResponse struct {
	Beacons []BeaconStatus `json:"beacons"`
	Total   int            `json:"total"`
}

// BeaconMetadata defines model for BeaconMetadata.
type BeaconMetadata struct {
	// Hostname RFC 1123 hostname pattern. Strict validation defends against stored XSS in the admin UI's beacon list (defence-in-depth — the UI must also escape on render).
	Hostname string           `json:"hostname"`
	Os       BeaconMetadataOs `json:"os"`

	// Version Beacon binary semver.
	Version string `json:"version"`
}

// BeaconMetadataOs defines model for BeaconMetadata.Os.
type BeaconMetadataOs string

// BeaconStatus defines model for BeaconStatus.
type BeaconStatus struct {
	BeaconOs              *string            `json:"beacon_os"`
	BeaconVersion         *string            `json:"beacon_version"`
	CertFingerprintSha256 string             `json:"cert_fingerprint_sha256"`
	CertNotAfter          time.Time          `json:"cert_not_after"`
	CertNotBefore         time.Time          `json:"cert_not_before"`
	CertSerial            string             `json:"cert_serial"`
	CreatedAt             time.Time          `json:"created_at"`
	DataKeyVersion        int                `json:"data_key_version"`
	Id                    openapi_types.UUID `json:"id"`
	LastClockSkewSeconds  *float32           `json:"last_clock_skew_seconds"`
	LastConfigHash        *string            `json:"last_config_hash"`
	LastSeenAt            *time.Time         `json:"last_seen_at"`
	Name                  string             `json:"name"`

	// PendingRestartRequired True when the beacon has received a config containing non-hot-reloadable fields (e.g., syslog/netflow listen addresses) that require a process restart to apply. Derived server-side by comparing the config hash the beacon reported in its last heartbeat (`pending_config_hash`) against the current `beacon_configs.config_hash`, then checking whether the diff touches any restart-required fields. Surfaced as an actionable alert in the admin UI.
	PendingRestartRequired *bool              `json:"pending_restart_required,omitempty"`
	Status                 BeaconStatusStatus `json:"status"`
	TenantId               string             `json:"tenant_id"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

// BeaconStatusStatus defines model for BeaconStatus.Status.
type BeaconStatusStatus string

// CertRotateRequest defines model for CertRotateRequest.
type CertRotateRequest struct {
	CsrPem string `json:"csr_pem"`
}

// CertRotateResponse defines model for CertRotateResponse.
type CertRotateResponse struct {
	CaCertPem        string    `json:"ca_cert_pem"`
	ClientCertPem    string    `json:"client_cert_pem"`
	GracePeriodHours int       `json:"grace_period_hours"`
	ValidFrom        time.Time `json:"valid_from"`
	ValidUntil       time.Time `json:"valid_until"`
}

// CertStatusResponse defines model for CertStatusResponse.
type CertStatusResponse struct {
	DaysUntilExpiry   int                                 `json:"days_until_expiry"`
	ExpiresAt         time.Time                           `json:"expires_at"`
	RecommendedAction CertStatusResponseRecommendedAction `json:"recommended_action"`
	RevocationReason  *string                             `json:"revocation_reason"`
	Valid             bool                                `json:"valid"`
}

// CertStatusResponseRecommendedAction defines model for CertStatusResponse.RecommendedAction.
type CertStatusResponseRecommendedAction string

// DeviceLatencyProbe defines model for DeviceLatencyProbe.
type DeviceLatencyProbe struct {
	DeviceIp        string  `json:"device_ip"`
	MedianLatencyMs float32 `json:"median_latency_ms"`
	ProbeCount      int     `json:"probe_count"`
}

// EncryptedEnvelope AES-256-GCM-encrypted blob per ADR-068. Byte layout:
//
// ```
// +-1B-+-1B-+-12B-+--N--+-16B-+
// | 01 | dv | iv  | ct  | tag |
// +----+----+-----+-----+-----+
// ```
//
// - byte 0: protocol version (`0x01`)
// - byte 1: DEK version (matches `data_key_version` in `beacon_registrations`)
// - bytes 2–13: 96-bit random IV (never reused with the same key)
// - bytes 14..(N-16): ciphertext
// - last 16 bytes: GCM auth tag
//
// AAD = Idempotency-Key UUIDv5 || data_key_version byte.
// Plaintext content type is advertised in the request `Content-Type` header
// (gzip-NDJSON for logs, JSON for SNMP/configs, raw nfcapd for flows).
type EncryptedEnvelope = openapi_types.File

// EnrollmentTokenCreate defines model for EnrollmentTokenCreate.
type EnrollmentTokenCreate struct {
	// Name Operator-supplied beacon display name.
	Name     string `json:"name"`
	TtlHours *int   `json:"ttl_hours,omitempty"`
}

// EnrollmentTokenListItem defines model for EnrollmentTokenListItem.
type EnrollmentTokenListItem struct {
	CreatedAt         time.Time          `json:"created_at"`
	CreatedByUsername string             `json:"created_by_username"`
	ExpiresAt         time.Time          `json:"expires_at"`
	Name              string             `json:"name"`
	RevokedAt         *time.Time         `json:"revoked_at"`
	TokenId           openapi_types.UUID `json:"token_id"`
	TokenPrefix       string             `json:"token_prefix"`
	UsedAt            *time.Time         `json:"used_at"`
}

// EnrollmentTokenResponse defines model for EnrollmentTokenResponse.
type EnrollmentTokenResponse struct {
	// BootstrapToken Plaintext token. Shown ONCE.
	BootstrapToken string `json:"bootstrap_token"`

	// EnrollmentBundle Base64-encoded JSON bundle (token + platform CA cert + endpoint URL, ed25519-signed).
	EnrollmentBundle []byte             `json:"enrollment_bundle"`
	ExpiresAt        time.Time          `json:"expires_at"`
	TokenId          openapi_types.UUID `json:"token_id"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code Stable string identifier (e.g. `BEACON_TOKEN_EXPIRED`).
		Code string `json:"code"`

		// Details Optional structured context.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Human-readable description.
		Message string `json:"message"`
	} `json:"error"`
}

// SimpleError Used on data-plane endpoints where the request body is opaque encrypted data.
type SimpleError struct {
	Detail string `json:"detail"`
}

// BeaconUrlCertMismatch defines model for BeaconUrlCertMismatch.
type BeaconUrlCertMismatch = Error

// NotFoundOrCrossTenant defines model for NotFoundOrCrossTenant.
type NotFoundOrCrossTenant = Error

// ListBeaconsParams defines parameters for ListBeacons.
type ListBeaconsParams struct {
	Cursor *openapi_types.UUID `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// PollBeaconConfigParams defines parameters for PollBeaconConfig.
type PollBeaconConfigParams struct {
	// IfNoneMatch Last-known config_hash. If matches current, returns 304.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// PushBeaconConfigsParams defines parameters for PushBeaconConfigs.
type PushBeaconConfigsParams struct {
	IdempotencyKey    openapi_types.UUID `json:"Idempotency-Key"`
	XBeaconDEKVersion int                `json:"X-Beacon-DEK-Version"`
}

// PushBeaconFlowsMultipartBody defines parameters for PushBeaconFlows.
type PushBeaconFlowsMultipartBody struct {
	Files []openapi_types.File `json:"files"`
}

// PushBeaconFlowsParams defines parameters for PushBeaconFlows.
type PushBeaconFlowsParams struct {
	IdempotencyKey    openapi_types.UUID `json:"Idempotency-Key"`
	XBeaconDEKVersion int                `json:"X-Beacon-DEK-Version"`
}

// PushBeaconLogsParams defines parameters for PushBeaconLogs.
type PushBeaconLogsParams struct {
	// IdempotencyKey UUIDv5 of `(beacon_id || sha256(plaintext_payload))`.
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`

	// XBeaconDEKVersion DEK version used for encryption (matches byte 1 of the body).
	XBeaconDEKVersion int `json:"X-Beacon-DEK-Version"`
}

// PushBeaconSnmpParams defines parameters for PushBeaconSnmp.
type PushBeaconSnmpParams struct {
	IdempotencyKey    openapi_types.UUID `json:"Idempotency-Key"`
	XBeaconDEKVersion int                `json:"X-Beacon-DEK-Version"`
}

// EnrollBeaconJSONRequestBody defines body for EnrollBeacon for application/json ContentType.
type EnrollBeaconJSONRequestBody = BeaconEnrollRequest

// CreateEnrollmentTokenJSONRequestBody defines body for CreateEnrollmentToken for application/json ContentType.
type CreateEnrollmentTokenJSONRequestBody = EnrollmentTokenCreate

// RotateBeaconCertJSONRequestBody defines body for RotateBeaconCert for application/json ContentType.
type RotateBeaconCertJSONRequestBody = CertRotateRequest

// UpdateBeaconConfigJSONRequestBody defines body for UpdateBeaconConfig for application/json ContentType.
type UpdateBeaconConfigJSONRequestBody = BeaconConfig

// PushBeaconFlowsMultipartRequestBody defines body for PushBeaconFlows for multipart/form-data ContentType.
type PushBeaconFlowsMultipartRequestBody PushBeaconFlowsMultipartBody

// PostBeaconHeartbeatJSONRequestBody defines body for PostBeaconHeartbeat for application/json ContentType.
type PostBeaconHeartbeatJSONRequestBody = BeaconHeartbeatRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListBeacons request
	ListBeacons(ctx context.Context, params *ListBeaconsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EnrollBeaconWithBody request with any body
	EnrollBeaconWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EnrollBeacon(ctx context.Context, body EnrollBeaconJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListEnrollmentTokens request
	ListEnrollmentTokens(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateEnrollmentTokenWithBody request with any body
	CreateEnrollmentTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateEnrollmentToken(ctx context.Context, body CreateEnrollmentTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeEnrollmentToken request
	RevokeEnrollmentToken(ctx context.Context, tokenId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeBeacon request
	RevokeBeacon(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBeacon request
	GetBeacon(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCertStatus request
	GetCertStatus(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RotateBeaconCertWithBody request with any body
	RotateBeaconCertWithBody(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RotateBeaconCert(ctx context.Context, beaconId openapi_types.UUID, body RotateBeaconCertJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PollBeaconConfig request
	PollBeaconConfig(ctx context.Context, beaconId openapi_types.UUID, params *PollBeaconConfigParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateBeaconConfigWithBody request with any body
	UpdateBeaconConfigWithBody(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateBeaconConfig(ctx context.Context, beaconId openapi_types.UUID, body UpdateBeaconConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PushBeaconConfigsWithBody request with any body
	PushBeaconConfigsWithBody(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconConfigsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PushBeaconFlowsWithBody request with any body
	PushBeaconFlowsWithBody(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconFlowsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PushBeaconLogsWithBody request with any body
	PushBeaconLogsWithBody(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconLogsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PushBeaconSnmpWithBody request with any body
	PushBeaconSnmpWithBody(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconSnmpParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostBeaconHeartbeatWithBody request with any body
	PostBeaconHeartbeatWithBody(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostBeaconHeartbeat(ctx context.Context, beaconId openapi_types.UUID, body PostBeaconHeartbeatJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RotateBeaconDataKey request
	RotateBeaconDataKey(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListBeacons(ctx context.Context, params *ListBeaconsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBeaconsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EnrollBeaconWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnrollBeaconRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EnrollBeacon(ctx context.Context, body EnrollBeaconJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnrollBeaconRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListEnrollmentTokens(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEnrollmentTokensRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateEnrollmentTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEnrollmentTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateEnrollmentToken(ctx context.Context, body CreateEnrollmentTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEnrollmentTokenRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeEnrollmentToken(ctx context.Context, tokenId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeEnrollmentTokenRequest(c.Server, tokenId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeBeacon(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeBeaconRequest(c.Server, beaconId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBeacon(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBeaconRequest(c.Server, beaconId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCertStatus(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCertStatusRequest(c.Server, beaconId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RotateBeaconCertWithBody(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRotateBeaconCertRequestWithBody(c.Server, beaconId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RotateBeaconCert(ctx context.Context, beaconId openapi_types.UUID, body RotateBeaconCertJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRotateBeaconCertRequest(c.Server, beaconId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PollBeaconConfig(ctx context.Context, beaconId openapi_types.UUID, params *PollBeaconConfigParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPollBeaconConfigRequest(c.Server, beaconId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateBeaconConfigWithBody(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateBeaconConfigRequestWithBody(c.Server, beaconId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateBeaconConfig(ctx context.Context, beaconId openapi_types.UUID, body UpdateBeaconConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateBeaconConfigRequest(c.Server, beaconId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushBeaconConfigsWithBody(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconConfigsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushBeaconConfigsRequestWithBody(c.Server, beaconId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushBeaconFlowsWithBody(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconFlowsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushBeaconFlowsRequestWithBody(c.Server, beaconId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushBeaconLogsWithBody(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconLogsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushBeaconLogsRequestWithBody(c.Server, beaconId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PushBeaconSnmpWithBody(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconSnmpParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushBeaconSnmpRequestWithBody(c.Server, beaconId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostBeaconHeartbeatWithBody(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBeaconHeartbeatRequestWithBody(c.Server, beaconId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostBeaconHeartbeat(ctx context.Context, beaconId openapi_types.UUID, body PostBeaconHeartbeatJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBeaconHeartbeatRequest(c.Server, beaconId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RotateBeaconDataKey(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRotateBeaconDataKeyRequest(c.Server, beaconId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListBeaconsRequest generates requests for ListBeacons
func NewListBeaconsRequest(server string, params *ListBeaconsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewEnrollBeaconRequest calls the generic EnrollBeacon builder with application/json body
func NewEnrollBeaconRequest(server string, body EnrollBeaconJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEnrollBeaconRequestWithBody(server, "application/json", bodyReader)
}

// NewEnrollBeaconRequestWithBody generates requests for EnrollBeacon with any type of body
func NewEnrollBeaconRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/enroll")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListEnrollmentTokensRequest generates requests for ListEnrollmentTokens
func NewListEnrollmentTokensRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/enrollment-tokens")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateEnrollmentTokenRequest calls the generic CreateEnrollmentToken builder with application/json body
func NewCreateEnrollmentTokenRequest(server string, body CreateEnrollmentTokenJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateEnrollmentTokenRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateEnrollmentTokenRequestWithBody generates requests for CreateEnrollmentToken with any type of body
func NewCreateEnrollmentTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/enrollment-tokens")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRevokeEnrollmentTokenRequest generates requests for RevokeEnrollmentToken
func NewRevokeEnrollmentTokenRequest(server string, tokenId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "token_id", runtime.ParamLocationPath, tokenId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/enrollment-tokens/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRevokeBeaconRequest generates requests for RevokeBeacon
func NewRevokeBeaconRequest(server string, beaconId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBeaconRequest generates requests for GetBeacon
func NewGetBeaconRequest(server string, beaconId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCertStatusRequest generates requests for GetCertStatus
func NewGetCertStatusRequest(server string, beaconId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s/cert-status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRotateBeaconCertRequest calls the generic RotateBeaconCert builder with application/json body
func NewRotateBeaconCertRequest(server string, beaconId openapi_types.UUID, body RotateBeaconCertJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRotateBeaconCertRequestWithBody(server, beaconId, "application/json", bodyReader)
}

// NewRotateBeaconCertRequestWithBody generates requests for RotateBeaconCert with any type of body
func NewRotateBeaconCertRequestWithBody(server string, beaconId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s/cert/rotate", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPollBeaconConfigRequest generates requests for PollBeaconConfig
func NewPollBeaconConfigRequest(server string, beaconId openapi_types.UUID, params *PollBeaconConfigParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s/config", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfNoneMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "If-None-Match", runtime.ParamLocationHeader, *params.IfNoneMatch)
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-None-Match", headerParam0)
		}

	}

	return req, nil
}

// NewUpdateBeaconConfigRequest calls the generic UpdateBeaconConfig builder with application/json body
func NewUpdateBeaconConfigRequest(server string, beaconId openapi_types.UUID, body UpdateBeaconConfigJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateBeaconConfigRequestWithBody(server, beaconId, "application/json", bodyReader)
}

// NewUpdateBeaconConfigRequestWithBody generates requests for UpdateBeaconConfig with any type of body
func NewUpdateBeaconConfigRequestWithBody(server string, beaconId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s/config", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPushBeaconConfigsRequestWithBody generates requests for PushBeaconConfigs with any type of body
func NewPushBeaconConfigsRequestWithBody(server string, beaconId openapi_types.UUID, params *PushBeaconConfigsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s/data/configs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Idempotency-Key", runtime.ParamLocationHeader, params.IdempotencyKey)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-Beacon-DEK-Version", runtime.ParamLocationHeader, params.XBeaconDEKVersion)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Beacon-DEK-Version", headerParam1)

	}

	return req, nil
}

// NewPushBeaconFlowsRequestWithBody generates requests for PushBeaconFlows with any type of body
func NewPushBeaconFlowsRequestWithBody(server string, beaconId openapi_types.UUID, params *PushBeaconFlowsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s/data/flows", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Idempotency-Key", runtime.ParamLocationHeader, params.IdempotencyKey)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-Beacon-DEK-Version", runtime.ParamLocationHeader, params.XBeaconDEKVersion)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Beacon-DEK-Version", headerParam1)

	}

	return req, nil
}

// NewPushBeaconLogsRequestWithBody generates requests for PushBeaconLogs with any type of body
func NewPushBeaconLogsRequestWithBody(server string, beaconId openapi_types.UUID, params *PushBeaconLogsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s/data/logs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Idempotency-Key", runtime.ParamLocationHeader, params.IdempotencyKey)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-Beacon-DEK-Version", runtime.ParamLocationHeader, params.XBeaconDEKVersion)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Beacon-DEK-Version", headerParam1)

	}

	return req, nil
}

// NewPushBeaconSnmpRequestWithBody generates requests for PushBeaconSnmp with any type of body
func NewPushBeaconSnmpRequestWithBody(server string, beaconId openapi_types.UUID, params *PushBeaconSnmpParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s/data/snmp", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Idempotency-Key", runtime.ParamLocationHeader, params.IdempotencyKey)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-Beacon-DEK-Version", runtime.ParamLocationHeader, params.XBeaconDEKVersion)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Beacon-DEK-Version", headerParam1)

	}

	return req, nil
}

// NewPostBeaconHeartbeatRequest calls the generic PostBeaconHeartbeat builder with application/json body
func NewPostBeaconHeartbeatRequest(server string, beaconId openapi_types.UUID, body PostBeaconHeartbeatJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostBeaconHeartbeatRequestWithBody(server, beaconId, "application/json", bodyReader)
}

// NewPostBeaconHeartbeatRequestWithBody generates requests for PostBeaconHeartbeat with any type of body
func NewPostBeaconHeartbeatRequestWithBody(server string, beaconId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s/heartbeat", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRotateBeaconDataKeyRequest generates requests for RotateBeaconDataKey
func NewRotateBeaconDataKeyRequest(server string, beaconId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "beacon_id", runtime.ParamLocationPath, beaconId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/beacons/%s/rotate-key", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListBeaconsWithResponse request
	ListBeaconsWithResponse(ctx context.Context, params *ListBeaconsParams, reqEditors ...RequestEditorFn) (*ListBeaconsResponse, error)

	// EnrollBeaconWithBodyWithResponse request with any body
	EnrollBeaconWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnrollBeaconResponse, error)

	EnrollBeaconWithResponse(ctx context.Context, body EnrollBeaconJSONRequestBody, reqEditors ...RequestEditorFn) (*EnrollBeaconResponse, error)

	// ListEnrollmentTokensWithResponse request
	ListEnrollmentTokensWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListEnrollmentTokensResponse, error)

	// CreateEnrollmentTokenWithBodyWithResponse request with any body
	CreateEnrollmentTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEnrollmentTokenResponse, error)

	CreateEnrollmentTokenWithResponse(ctx context.Context, body CreateEnrollmentTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEnrollmentTokenResponse, error)

	// RevokeEnrollmentTokenWithResponse request
	RevokeEnrollmentTokenWithResponse(ctx context.Context, tokenId openapi_types.UUID, reqEditors ...RequestEditorFn) (*RevokeEnrollmentTokenResponse, error)

	// RevokeBeaconWithResponse request
	RevokeBeaconWithResponse(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*RevokeBeaconResponse, error)

	// GetBeaconWithResponse request
	GetBeaconWithResponse(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetBeaconResponse, error)

	// GetCertStatusWithResponse request
	GetCertStatusWithResponse(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetCertStatusResponse, error)

	// RotateBeaconCertWithBodyWithResponse request with any body
	RotateBeaconCertWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RotateBeaconCertResponse, error)

	RotateBeaconCertWithResponse(ctx context.Context, beaconId openapi_types.UUID, body RotateBeaconCertJSONRequestBody, reqEditors ...RequestEditorFn) (*RotateBeaconCertResponse, error)

	// PollBeaconConfigWithResponse request
	PollBeaconConfigWithResponse(ctx context.Context, beaconId openapi_types.UUID, params *PollBeaconConfigParams, reqEditors ...RequestEditorFn) (*PollBeaconConfigResponse, error)

	// UpdateBeaconConfigWithBodyWithResponse request with any body
	UpdateBeaconConfigWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateBeaconConfigResponse, error)

	UpdateBeaconConfigWithResponse(ctx context.Context, beaconId openapi_types.UUID, body UpdateBeaconConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateBeaconConfigResponse, error)

	// PushBeaconConfigsWithBodyWithResponse request with any body
	PushBeaconConfigsWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconConfigsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushBeaconConfigsResponse, error)

	// PushBeaconFlowsWithBodyWithResponse request with any body
	PushBeaconFlowsWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconFlowsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushBeaconFlowsResponse, error)

	// PushBeaconLogsWithBodyWithResponse request with any body
	PushBeaconLogsWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconLogsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushBeaconLogsResponse, error)

	// PushBeaconSnmpWithBodyWithResponse request with any body
	PushBeaconSnmpWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconSnmpParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushBeaconSnmpResponse, error)

	// PostBeaconHeartbeatWithBodyWithResponse request with any body
	PostBeaconHeartbeatWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostBeaconHeartbeatResponse, error)

	PostBeaconHeartbeatWithResponse(ctx context.Context, beaconId openapi_types.UUID, body PostBeaconHeartbeatJSONRequestBody, reqEditors ...RequestEditorFn) (*PostBeaconHeartbeatResponse, error)

	// RotateBeaconDataKeyWithResponse request
	RotateBeaconDataKeyWithResponse(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*RotateBeaconDataKeyResponse, error)
}

type ListBeaconsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BeaconListResponse
}

// Status returns HTTPResponse.Status
func (r ListBeaconsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBeaconsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type EnrollBeaconResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *BeaconEnrollResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r EnrollBeaconResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EnrollBeaconResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListEnrollmentTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]EnrollmentTokenListItem
}

// Status returns HTTPResponse.Status
func (r ListEnrollmentTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEnrollmentTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateEnrollmentTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *EnrollmentTokenResponse
	JSON401      *Error
}

// Status returns HTTPResponse.Status
func (r CreateEnrollmentTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateEnrollmentTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RevokeEnrollmentTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *NotFoundOrCrossTenant
}

// Status returns HTTPResponse.Status
func (r RevokeEnrollmentTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeEnrollmentTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RevokeBeaconResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *NotFoundOrCrossTenant
}

// Status returns HTTPResponse.Status
func (r RevokeBeaconResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeBeaconResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBeaconResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BeaconStatus
	JSON404      *NotFoundOrCrossTenant
}

// Status returns HTTPResponse.Status
func (r GetBeaconResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBeaconResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCertStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CertStatusResponse
	JSON403      *BeaconUrlCertMismatch
}

// Status returns HTTPResponse.Status
func (r GetCertStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCertStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RotateBeaconCertResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CertRotateResponse
	JSON403      *BeaconUrlCertMismatch
}

// Status returns HTTPResponse.Status
func (r RotateBeaconCertResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RotateBeaconCertResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PollBeaconConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BeaconConfigResponse
	JSON403      *BeaconUrlCertMismatch
}

// Status returns HTTPResponse.Status
func (r PollBeaconConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PollBeaconConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateBeaconConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BeaconConfigResponse
	JSON404      *NotFoundOrCrossTenant
}

// Status returns HTTPResponse.Status
func (r UpdateBeaconConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateBeaconConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PushBeaconConfigsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON403      *BeaconUrlCertMismatch
}

// Status returns HTTPResponse.Status
func (r PushBeaconConfigsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PushBeaconConfigsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PushBeaconFlowsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON403      *BeaconUrlCertMismatch
}

// Status returns HTTPResponse.Status
func (r PushBeaconFlowsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PushBeaconFlowsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PushBeaconLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON403      *BeaconUrlCertMismatch
	JSON413      *SimpleError
}

// Status returns HTTPResponse.Status
func (r PushBeaconLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PushBeaconLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PushBeaconSnmpResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON403      *BeaconUrlCertMismatch
}

// Status returns HTTPResponse.Status
func (r PushBeaconSnmpResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PushBeaconSnmpResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostBeaconHeartbeatResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON403      *BeaconUrlCertMismatch
}

// Status returns HTTPResponse.Status
func (r PostBeaconHeartbeatResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostBeaconHeartbeatResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RotateBeaconDataKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *NotFoundOrCrossTenant
}

// Status returns HTTPResponse.Status
func (r RotateBeaconDataKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RotateBeaconDataKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListBeaconsWithResponse request returning *ListBeaconsResponse
func (c *ClientWithResponses) ListBeaconsWithResponse(ctx context.Context, params *ListBeaconsParams, reqEditors ...RequestEditorFn) (*ListBeaconsResponse, error) {
	rsp, err := c.ListBeacons(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBeaconsResponse(rsp)
}

// EnrollBeaconWithBodyWithResponse request with arbitrary body returning *EnrollBeaconResponse
func (c *ClientWithResponses) EnrollBeaconWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnrollBeaconResponse, error) {
	rsp, err := c.EnrollBeaconWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnrollBeaconResponse(rsp)
}

func (c *ClientWithResponses) EnrollBeaconWithResponse(ctx context.Context, body EnrollBeaconJSONRequestBody, reqEditors ...RequestEditorFn) (*EnrollBeaconResponse, error) {
	rsp, err := c.EnrollBeacon(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnrollBeaconResponse(rsp)
}

// ListEnrollmentTokensWithResponse request returning *ListEnrollmentTokensResponse
func (c *ClientWithResponses) ListEnrollmentTokensWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListEnrollmentTokensResponse, error) {
	rsp, err := c.ListEnrollmentTokens(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEnrollmentTokensResponse(rsp)
}

// CreateEnrollmentTokenWithBodyWithResponse request with arbitrary body returning *CreateEnrollmentTokenResponse
func (c *ClientWithResponses) CreateEnrollmentTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEnrollmentTokenResponse, error) {
	rsp, err := c.CreateEnrollmentTokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEnrollmentTokenResponse(rsp)
}

func (c *ClientWithResponses) CreateEnrollmentTokenWithResponse(ctx context.Context, body CreateEnrollmentTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEnrollmentTokenResponse, error) {
	rsp, err := c.CreateEnrollmentToken(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEnrollmentTokenResponse(rsp)
}

// RevokeEnrollmentTokenWithResponse request returning *RevokeEnrollmentTokenResponse
func (c *ClientWithResponses) RevokeEnrollmentTokenWithResponse(ctx context.Context, tokenId openapi_types.UUID, reqEditors ...RequestEditorFn) (*RevokeEnrollmentTokenResponse, error) {
	rsp, err := c.RevokeEnrollmentToken(ctx, tokenId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeEnrollmentTokenResponse(rsp)
}

// RevokeBeaconWithResponse request returning *RevokeBeaconResponse
func (c *ClientWithResponses) RevokeBeaconWithResponse(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*RevokeBeaconResponse, error) {
	rsp, err := c.RevokeBeacon(ctx, beaconId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeBeaconResponse(rsp)
}

// GetBeaconWithResponse request returning *GetBeaconResponse
func (c *ClientWithResponses) GetBeaconWithResponse(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetBeaconResponse, error) {
	rsp, err := c.GetBeacon(ctx, beaconId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBeaconResponse(rsp)
}

// GetCertStatusWithResponse request returning *GetCertStatusResponse
func (c *ClientWithResponses) GetCertStatusWithResponse(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetCertStatusResponse, error) {
	rsp, err := c.GetCertStatus(ctx, beaconId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCertStatusResponse(rsp)
}

// RotateBeaconCertWithBodyWithResponse request with arbitrary body returning *RotateBeaconCertResponse
func (c *ClientWithResponses) RotateBeaconCertWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RotateBeaconCertResponse, error) {
	rsp, err := c.RotateBeaconCertWithBody(ctx, beaconId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRotateBeaconCertResponse(rsp)
}

func (c *ClientWithResponses) RotateBeaconCertWithResponse(ctx context.Context, beaconId openapi_types.UUID, body RotateBeaconCertJSONRequestBody, reqEditors ...RequestEditorFn) (*RotateBeaconCertResponse, error) {
	rsp, err := c.RotateBeaconCert(ctx, beaconId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRotateBeaconCertResponse(rsp)
}

// PollBeaconConfigWithResponse request returning *PollBeaconConfigResponse
func (c *ClientWithResponses) PollBeaconConfigWithResponse(ctx context.Context, beaconId openapi_types.UUID, params *PollBeaconConfigParams, reqEditors ...RequestEditorFn) (*PollBeaconConfigResponse, error) {
	rsp, err := c.PollBeaconConfig(ctx, beaconId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePollBeaconConfigResponse(rsp)
}

// UpdateBeaconConfigWithBodyWithResponse request with arbitrary body returning *UpdateBeaconConfigResponse
func (c *ClientWithResponses) UpdateBeaconConfigWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateBeaconConfigResponse, error) {
	rsp, err := c.UpdateBeaconConfigWithBody(ctx, beaconId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateBeaconConfigResponse(rsp)
}

func (c *ClientWithResponses) UpdateBeaconConfigWithResponse(ctx context.Context, beaconId openapi_types.UUID, body UpdateBeaconConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateBeaconConfigResponse, error) {
	rsp, err := c.UpdateBeaconConfig(ctx, beaconId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateBeaconConfigResponse(rsp)
}

// PushBeaconConfigsWithBodyWithResponse request with arbitrary body returning *PushBeaconConfigsResponse
func (c *ClientWithResponses) PushBeaconConfigsWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconConfigsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushBeaconConfigsResponse, error) {
	rsp, err := c.PushBeaconConfigsWithBody(ctx, beaconId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushBeaconConfigsResponse(rsp)
}

// PushBeaconFlowsWithBodyWithResponse request with arbitrary body returning *PushBeaconFlowsResponse
func (c *ClientWithResponses) PushBeaconFlowsWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconFlowsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushBeaconFlowsResponse, error) {
	rsp, err := c.PushBeaconFlowsWithBody(ctx, beaconId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushBeaconFlowsResponse(rsp)
}

// PushBeaconLogsWithBodyWithResponse request with arbitrary body returning *PushBeaconLogsResponse
func (c *ClientWithResponses) PushBeaconLogsWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconLogsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushBeaconLogsResponse, error) {
	rsp, err := c.PushBeaconLogsWithBody(ctx, beaconId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushBeaconLogsResponse(rsp)
}

// PushBeaconSnmpWithBodyWithResponse request with arbitrary body returning *PushBeaconSnmpResponse
func (c *ClientWithResponses) PushBeaconSnmpWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, params *PushBeaconSnmpParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushBeaconSnmpResponse, error) {
	rsp, err := c.PushBeaconSnmpWithBody(ctx, beaconId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushBeaconSnmpResponse(rsp)
}

// PostBeaconHeartbeatWithBodyWithResponse request with arbitrary body returning *PostBeaconHeartbeatResponse
func (c *ClientWithResponses) PostBeaconHeartbeatWithBodyWithResponse(ctx context.Context, beaconId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostBeaconHeartbeatResponse, error) {
	rsp, err := c.PostBeaconHeartbeatWithBody(ctx, beaconId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBeaconHeartbeatResponse(rsp)
}

func (c *ClientWithResponses) PostBeaconHeartbeatWithResponse(ctx context.Context, beaconId openapi_types.UUID, body PostBeaconHeartbeatJSONRequestBody, reqEditors ...RequestEditorFn) (*PostBeaconHeartbeatResponse, error) {
	rsp, err := c.PostBeaconHeartbeat(ctx, beaconId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBeaconHeartbeatResponse(rsp)
}

// RotateBeaconDataKeyWithResponse request returning *RotateBeaconDataKeyResponse
func (c *ClientWithResponses) RotateBeaconDataKeyWithResponse(ctx context.Context, beaconId openapi_types.UUID, reqEditors ...RequestEditorFn) (*RotateBeaconDataKeyResponse, error) {
	rsp, err := c.RotateBeaconDataKey(ctx, beaconId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRotateBeaconDataKeyResponse(rsp)
}

// ParseListBeaconsResponse parses an HTTP response from a ListBeaconsWithResponse call
func ParseListBeaconsResponse(rsp *http.Response) (*ListBeaconsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBeaconsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BeaconListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseEnrollBeaconResponse parses an HTTP response from a EnrollBeaconWithResponse call
func ParseEnrollBeaconResponse(rsp *http.Response) (*EnrollBeaconResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EnrollBeaconResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest BeaconEnrollResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseListEnrollmentTokensResponse parses an HTTP response from a ListEnrollmentTokensWithResponse call
func ParseListEnrollmentTokensResponse(rsp *http.Response) (*ListEnrollmentTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEnrollmentTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []EnrollmentTokenListItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateEnrollmentTokenResponse parses an HTTP response from a CreateEnrollmentTokenWithResponse call
func ParseCreateEnrollmentTokenResponse(rsp *http.Response) (*CreateEnrollmentTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateEnrollmentTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest EnrollmentTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseRevokeEnrollmentTokenResponse parses an HTTP response from a RevokeEnrollmentTokenWithResponse call
func ParseRevokeEnrollmentTokenResponse(rsp *http.Response) (*RevokeEnrollmentTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeEnrollmentTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundOrCrossTenant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRevokeBeaconResponse parses an HTTP response from a RevokeBeaconWithResponse call
func ParseRevokeBeaconResponse(rsp *http.Response) (*RevokeBeaconResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeBeaconResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundOrCrossTenant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetBeaconResponse parses an HTTP response from a GetBeaconWithResponse call
func ParseGetBeaconResponse(rsp *http.Response) (*GetBeaconResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBeaconResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BeaconStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundOrCrossTenant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetCertStatusResponse parses an HTTP response from a GetCertStatusWithResponse call
func ParseGetCertStatusResponse(rsp *http.Response) (*GetCertStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCertStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BeaconUrlCertMismatch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseRotateBeaconCertResponse parses an HTTP response from a RotateBeaconCertWithResponse call
func ParseRotateBeaconCertResponse(rsp *http.Response) (*RotateBeaconCertResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RotateBeaconCertResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CertRotateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BeaconUrlCertMismatch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePollBeaconConfigResponse parses an HTTP response from a PollBeaconConfigWithResponse call
func ParsePollBeaconConfigResponse(rsp *http.Response) (*PollBeaconConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PollBeaconConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BeaconConfigResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BeaconUrlCertMismatch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseUpdateBeaconConfigResponse parses an HTTP response from a UpdateBeaconConfigWithResponse call
func ParseUpdateBeaconConfigResponse(rsp *http.Response) (*UpdateBeaconConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateBeaconConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BeaconConfigResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundOrCrossTenant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePushBeaconConfigsResponse parses an HTTP response from a PushBeaconConfigsWithResponse call
func ParsePushBeaconConfigsResponse(rsp *http.Response) (*PushBeaconConfigsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PushBeaconConfigsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BeaconUrlCertMismatch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePushBeaconFlowsResponse parses an HTTP response from a PushBeaconFlowsWithResponse call
func ParsePushBeaconFlowsResponse(rsp *http.Response) (*PushBeaconFlowsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PushBeaconFlowsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BeaconUrlCertMismatch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePushBeaconLogsResponse parses an HTTP response from a PushBeaconLogsWithResponse call
func ParsePushBeaconLogsResponse(rsp *http.Response) (*PushBeaconLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PushBeaconLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BeaconUrlCertMismatch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest SimpleError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}

// ParsePushBeaconSnmpResponse parses an HTTP response from a PushBeaconSnmpWithResponse call
func ParsePushBeaconSnmpResponse(rsp *http.Response) (*PushBeaconSnmpResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PushBeaconSnmpResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BeaconUrlCertMismatch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePostBeaconHeartbeatResponse parses an HTTP response from a PostBeaconHeartbeatWithResponse call
func ParsePostBeaconHeartbeatResponse(rsp *http.Response) (*PostBeaconHeartbeatResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostBeaconHeartbeatResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BeaconUrlCertMismatch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseRotateBeaconDataKeyResponse parses an HTTP response from a RotateBeaconDataKeyWithResponse call
func ParseRotateBeaconDataKeyResponse(rsp *http.Response) (*RotateBeaconDataKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RotateBeaconDataKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundOrCrossTenant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
